name: Deploy to TestFlight

on:
  push:
    branches:
      - {{MAIN_BRANCH}}
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build number (optional, auto-increments if empty)'
        required: false
        type: string

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: macos-{{MACOS_VERSION}}
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for version detection

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_{{XCODE_VERSION}}.app

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install fastlane
          fastlane --version

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods dependencies
        if: hashFiles('Podfile') != ''
        run: pod install --repo-update

      - name: Setup App Store Connect API Key
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$ASC_KEY_CONTENT" > ~/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8

      - name: Install Certificates & Provisioning Profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          fastlane match appstore --readonly

      - name: Build and Upload to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          BUILD_NUMBER: ${{ github.event.inputs.build_number }}
        run: |
          fastlane beta

      - name: Upload dSYM to Crashlytics (optional)
        if: hashFiles('**/GoogleService-Info.plist') != ''
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          fastlane upload_symbols || echo "dSYM upload skipped"

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Successfully deployed to TestFlight!"
          echo "Commit: ${{ github.sha }}"
          echo "Build triggered by: ${{ github.actor }}"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ TestFlight deployment failed!"
          echo "Commit: ${{ github.sha }}"
