name: Build & Deploy

on:
  push:
    branches:
      - {{MAIN_BRANCH}}
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '{{NODE_VERSION}}'
          cache: 'npm'

      - name: Install dependencies
        run: {{INSTALL_DEPS_COMMAND}}

      - name: Build application
        run: {{BUILD_COMMAND}}
        env:
          NODE_ENV: production

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            set -e

            REPO_PATH="{{REPO_ROOT}}"
            DEPLOY_PATH="{{DEPLOY_PATH}}"
            BACKUP_DIR="/var/backups"
            BACKUP_PREFIX="{{BACKUP_PREFIX}}"
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            BACKUP_PATH="$BACKUP_DIR/${BACKUP_PREFIX}-${TIMESTAMP}"

            cd "$REPO_PATH"

            git fetch origin {{MAIN_BRANCH}}
            git reset --hard origin/{{MAIN_BRANCH}}

            {{INSTALL_DEPS_COMMAND}}

            {{BUILD_COMMAND}}

            if [ -d "$DEPLOY_PATH" ]; then
              echo "Creating backup..."
              mkdir -p "$BACKUP_DIR"
              cp -r "$DEPLOY_PATH" "$BACKUP_PATH"
            fi

            echo "Deploying new build..."
            mkdir -p "$DEPLOY_PATH"
            rsync -av --delete "$REPO_PATH/dist/" "$DEPLOY_PATH/"

            chown -R {{WEB_USER}}:{{WEB_GROUP}} "$DEPLOY_PATH"
            chmod -R 755 "$DEPLOY_PATH"

            echo "Deployment completed successfully!"
            echo "Backup saved to: $BACKUP_PATH"

      - name: Notify on success
        if: success()
        run: echo "✅ Deployment successful for commit ${{ github.sha }}"

      - name: Notify on failure
        if: failure()
        run: echo "❌ Deployment failed for commit ${{ github.sha }}"
